dataset:
  data_root: "dataset/data"
  image_dir: "images"
  condition_dir: "conditions"
  condition_threshold: 99

  target_width: 1280
  target_height: 720

condition:
  in_features: 4
  context_dim: 512
  num_tokens: 1024

attention:
  channel: 256
  query_dim: 4
  context_dim: 512
  num_heads: 8
  dropout: 0.0

unet:
  in_channels: 4
  out_channels: 4
  base_channels: 64
  depth: 4             # depth: 4 초과하면 안됨
  context_dim: int = 512

  channel_mults: [1, 2, 4, 8]
  num_res_blocks: 2
  attention_levels: [1, 2]
  use_fp16: true

training:
  batch_size: 16